# Gin-Vue-Admin Global Configuration

# jwt configuration
jwt:
  signing-key: 'dancin-api'
  expires-time: 604800
  buffer-time: 86400

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[GIN-VUE-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
report:
  path: "localhost:9092"
  topic: 'report'
  group: 'report'

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# system configuration
system:
  env: 'public'
  addr: 8889
  db-type: 'mysql'
  oss-type: 'local'
  use-multipoint: false
  use-middleware: 'kafka'

# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'push_platform'
  username: 'root'
  password: '123456'
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: true
  log-zap: false

# local configuration
local:
  path: 'uploads/file'